export const projects: Project[] = [
	{
		name: "仿 Arco Design Vue组件库",
		stacks: ["Vue3", "TypeScript", "Sass"],
		link: "https://arch-desgin.github.io/arch-ui-vue",
		git: "https://github.com/arch-desgin/arch-ui-vue",
		desc: "Arch UI Components Library，类 Arco Design UI 库，使用 Vue3 Setup + TS + Sass 技术栈构建。组件库能够广泛覆盖 Arco Design Vue 的功能，并且与 Arco Design Vue 的 API 兼容。提供简洁明了的 API 和组件结构，使开发人员能够快速上手并高效构建界面，减少开发时间和工作量。部分组件兼容多种开发范式。在线文档包含详细的组件文档和示例，以展示组件库的功能和使用方法。",
		imgs: [
			"https://picgo-img-repo.oss-cn-beijing.aliyuncs.com/img/79d7a9a120d0a8ee7938e6d0a4907e39.png",
			"https://picgo-img-repo.oss-cn-beijing.aliyuncs.com/img/7729f62825b40b85fe1426a975449e8b.png",
			"https://picgo-img-repo.oss-cn-beijing.aliyuncs.com/img/8c00db8bcb4d037c5504bea286d45f6a.png",
		],
		category: ["前端", "练手基建Demo"],
		createTime: "2024-11-03",
		updateTime: "2025-02-25",
		enable: true,
	},
	{
		name: "仿 axios 项目",
		stacks: [
			"JavaScript",
			"TypeScript",
			"Rollup",
			"ESLint",
			"Prettier",
			"Husky",
			"Vite",
			"React",
			"React-DOM",
			"Node.js",
		],
		link: "",
		git: "https://github.com/Healwrap/axios",
		desc: "本项目是一个关于 仿axios 的项目，包含多个包及配置文件。使用了 Rollup 进行构建，有丰富的开发和构建脚本，如清理、构建、发布等。使用 ESLint 和 Prettier 进行代码规范和格式化，Husky 进行 Git 钩子管理。部分子项目使用了 Vite 进行开发，并且依赖 React 等相关技术栈。",
		imgs: [],
		category: ["前端", "练手基建Demo"],
		createTime: "2024-11-17",
		updateTime: "2024-07-21",
		enable: true,
	},
	{
		name: "常青招聘",
		stacks: [
			"Vue3",
			"TypeScript",
			"Vite",
			"Ant-Design-Vue",
			"Echarts",
			"antv/g6",
			"Alova",
			"VueUse",
			"Sass",
			"TailwindCSS",
			"Eslint",
			"Prettier",
			"husky",
		],
		link: "https://eh.healwrap.cn/",
		git: "https://github.com/evergreen-recruitment/frontend",
		desc: "本项目为服创 A15 赛题的前端代码，力求前端页面的精致和优雅，保证用户具有优秀的体验。一改传统招聘网站简陋的页面，加入了大量新颖元素如分析简历、知识图谱、技能分析、技术栈分析、相关搜索、大数据算法推荐等。使用先进的前端技术栈，有严谨的代码规范和样式统一性，包括 Git 提交信息的规范和控制，并使用 AliyunFLow 进行 CI/CD，页面使用统一的主题色和圆角，有自适应的主题色和暗亮色模式。",
		imgs: [
			"https://picgo-img-repo.oss-cn-beijing.aliyuncs.com/img/3ba365b4526aa6f3e7f14575750cadfa.png",
			"https://picgo-img-repo.oss-cn-beijing.aliyuncs.com/img/4fe6668839f63f3f5ee5422272998bbf.png",
			"https://picgo-img-repo.oss-cn-beijing.aliyuncs.com/img/b4711c0c25923ddc51b19e6b324420b1.png",
			"https://picgo-img-repo.oss-cn-beijing.aliyuncs.com/img/dabf838dd40c1fae67d4352b66f91587.png",
			"https://picgo-img-repo.oss-cn-beijing.aliyuncs.com/img/7e4b57a10ae79ae2f252c8b8faf0d0c5.png",
			"https://picgo-img-repo.oss-cn-beijing.aliyuncs.com/img/17f9d03bff375f460099e7115a8903ec.png",
		],
		category: ["前端", "练手业务Demo"],
		createTime: "2024-03-07",
		updateTime: "2024-07-04",
		enable: true,
	},
	{
		name: "HealWrap · 愈屋",
		stacks: [
			"Vue",
			"Vite",
			"Springboot",
			"JavaScript",
			"Java",
			"Sass",
			"TailwindCSS",
			"Eslint",
			"Prettier",
		],
		link: "",
		git: "https://github.com/Healwrap/hp-blog",
		desc: "HealWrap 是基于 Spring Boot 和 Vue 构建的博客论坛系统。用户未登录可浏览文章，登录后能点赞、评论、下载附件等。其涵盖注册登录、首页文章及板块展示、文章详情操作、文章创作编辑、用户中心资料与积分管理、消息中心查看消息等功能，为用户提供了一个集内容分享、交流互动、个人信息管理于一体的综合性平台。 ",
		imgs: [
			"https://picgo-img-repo.oss-cn-beijing.aliyuncs.com/img/76923a7541aded7e4c6352c604fea22c.png",
			"https://picgo-img-repo.oss-cn-beijing.aliyuncs.com/img/bfc47aabe1a66af78c80bbcdaafc7ec2.png",
			"https://picgo-img-repo.oss-cn-beijing.aliyuncs.com/img/8e078781dc4dfd9d0d3059c272cafb66.png",
			"https://picgo-img-repo.oss-cn-beijing.aliyuncs.com/img/f17b7c32af73b0c185c1241df0bdaf03.png",
			"https://picgo-img-repo.oss-cn-beijing.aliyuncs.com/img/cb8e9a1ab640129f11f67be511f95f7f.png",
		],
		category: ["前端", "后端", "练手业务Demo"],
		createTime: "2023-04-12",
		updateTime: "2023-06-18",
		enable: true,
	},
	// 可以添加更多项目
];
